### ISSUE TITLE
Installer.exe is not saving the PNGs

### ISSUE THREAD

**Issue by seyo-IV** [DizzyduckAR/Bot-It-Pokemon-masters#1]

**Comment by seyo-IV** [comment]
BotIt Pokemon Masters 0.4.9.5 is creating the PNGs but not loading during runtime.

**Comment by seyo-IV** [comment]
The same happens to me with BotIt_Pokemon_Masters_0.4.9.6. May that be because I have 2 monitors?

**Comment by seyo-IV** [comment]
it's strange because it worked at work...

**Comment by seyo-IV** [comment]
In the latest version its saying Botit1.PNG not found and so on, but I actually have those.

**Comment by seyo-IV** [comment]
<img width="204" alt="test" src="https://user-images.githubusercontent.com/32060944/65984531-4240ca80-e480-11e9-8785-d05bfdaab094.png">
also this dont look okay to me, thats the test.PNG

**Comment by DizzyduckAR** [comment]
1) this git is not up to date.
jump on discord we are on 0.5.35.

2) can be a system zoom issue.
0.5.35 will show you what botit see

**Comment by seyo-IV** [comment]
k will check it
